--TRAINERGENERATORSTART--
--This is autogenerated code. Changing code in this block will
--get erased and rewritten if you regenerate the trainer code

--Uncomment the following line if this is a Cheat Table format trainer and you don't want CE to show (Tip, save as .CETRAINER alternatively)
--hideAllCEWindows()

RequiredCEVersion=7.4
if (getCEVersion==nil) or (getCEVersion()<RequiredCEVersion) then
  messageDialog('Please install Cheat Engine '..RequiredCEVersion, mtError, mbOK)
  closeCE()
end
getAutoAttachList().add("EoCApp.exe")
--these where throwing an error so they have been commented
--addresslist=getAddressList()
--memrec0=addresslist.getMemoryRecordByID(0)


--reads values from game to be show in left most text boxes
function ButtonReadClick(sender)
  setProperty(UDF1.ReadMin,"Text", readFloat("[EoCApp.exe+2959898]+C40"))
  setProperty(UDF1.ReadMax1,"Text", readFloat("[EoCApp.exe+2959898]+C44"))
  setProperty(UDF1.ReadMax2,"Text", readFloat("[EoCApp.exe+2959898]+C48"))
end

--sets in game values with right minimum text box
function ButtonSetMinClick(sender)
  writeFloat("[EoCApp.exe+2959898]+C40", getProperty(UDF1.SetMinVal,"Text"))
end

--sets in game values with right maximum text box
function ButtonSetMaxClick(sender)
  writeFloat("[EoCApp.exe+2959898]+C44", getProperty(UDF1.SetMaxVal,"Text"))
  writeFloat("[EoCApp.exe+2959898]+C48", getProperty(UDF1.SetMaxVal,"Text"))
end

--sets both text boxes to default values then applies them to game to reset to defaults
function ButtonDefaults(sender)
  UDF1.SetMinVal.Text = '5.5'
  UDF1.SetMaxVal.Text = '19'
  writeFloat("[EoCApp.exe+2959898]+C40", getProperty(UDF1.SetMinVal,"Text"))
  writeFloat("[EoCApp.exe+2959898]+C44", getProperty(UDF1.SetMaxVal,"Text"))
  writeFloat("[EoCApp.exe+2959898]+C48", getProperty(UDF1.SetMaxVal,"Text"))
end

--read fov
function ButtonFOVReadClick(sender)
  setProperty(UDF1.FOVEdit,"Text", readFloat("[EoCApp.exe+2959898]+C74"))
end
--write fov
function ButtonFOVSetClick(sender)
  writeFloat("[EoCApp.exe+2959898]+C74", getProperty(UDF1.FOVEdit,"Text"))
end
--reset fov
function ButtonFOVResetClick(sender)
  UDF1.FOVEdit.Text = '45'
  writeFloat("[EoCApp.exe+2959898]+C74", getProperty(UDF1.FOVEdit,"Text"))
end


getAutoAttachList().add("EoCApp.exe")
gPlaySoundOnAction=false
--these where throwing an error so they have been commented
--CETrainer.SEPERATOR.Visible=false
--CETrainer.fixDPI() --remove this if you have already taken care of DPI issues yourself
--CETrainer.show()
--function AboutClick()
--  showMessage(gAboutText)
--end
--gAboutText=[[Beans]]

function CloseClick()
  --called by the close button onClick event, and when closing the form
  closeCE()
  return caFree --onClick doesn't care, but onClose would like a result
end

--TRAINERGENERATORSTOP--
